### ISSUE TITLE
Why tauri?

### ISSUE THREAD

**Issue by yeppiidev** [rishbobb/screensaver#1]
Is there any advantages using tauri over electron?

**Comment by rishabhroyy** [comment]
Not sure if there are any advantages. Just like it more. Also it stays loaded in the background (not sure if electron does the same)

**Comment by yeppiidev** [comment]
Pretty cool. Do you plan to release a version for Linux and Windows as well?

**Comment by rishabhroyy** [comment]
It works on all platforms!

**Comment by yeppiidev** [comment]
It does, but do you plan to release binaries for Linux and Windows?

**Comment by rishabhroyy** [comment]
I'm not sure if I will release binaries at all.
